package models

import (
	"time"

	"gorm.io/gorm"
)

// BaseModel replaces gorm.Model with a PostgreSQL IDENTITY-backed int64 primary
// key. GORM emits GENERATED BY DEFAULT AS IDENTITY via the autoIncrement tag,
// which Atlas picks up and writes as proper SQL-standard IDENTITY syntax in
// migrations (rather than the legacy SERIAL shorthand).
type BaseModel struct {
	ID        int64          `gorm:"primaryKey;autoIncrement"`
	CreatedAt time.Time      `gorm:"autoCreateTime"`
	UpdatedAt time.Time      `gorm:"autoUpdateTime"`
	DeletedAt gorm.DeletedAt `gorm:"index"` // gorm.DeletedAt enables soft-delete
}
